### ISSUE TITLE
Precompiler(Proposal)

### ISSUE THREAD

**Issue by mizchi** [jadejs/react-jade#29]
I created this project. https://github.com/mizchi/react-jade-precompiler

It's just dump of this.

```js
tmpl = jade.compileFile(fpath)
tmplStr = argv.header + tmpl.toString()
```

I know, it loses all local context and may fail trivial case but It's no problem in my use case.
If it can, I think this feature should be provided by react-jade project.  How about this?

**Comment by ForbesLindesay** [comment]
We have an API intended for doing just this called `jade.compileFileClient`.  We could consider adding a simple CLI, but it should probably be a separate project (perhaps still under the jade organisation though).
