### ISSUE TITLE
maxlength vs maxLength

### ISSUE THREAD

**Issue by DeeLindesay** [jadejs/react-jade#33]
When I use `maxlength` as an attribute I get this warning

> Warning: Unknown DOM property maxlength. Did you mean maxLength?

Could we make `maxlength` an alias for `maxLength`?

**Comment by hemanth** [comment]
Not really, `camelCase` is pretty intuitive.

**Comment by ForbesLindesay** [comment]
Yes, but the goal with react-jade is exact parity with jade, which supports the all lowercase version of maxlength, so it seems natural to support both, like we do with `for` => `htmlFor` and `class` => `className`.

**Comment by hemanth** [comment]
> parity with jade

:+1:
