### ISSUE TITLE
React 0.13

### ISSUE THREAD

**Issue by ai** [jadejs/react-jade#40]
@ForbesLindesay we need to update `react` `peerDependency` to `~0.13.0`.

BTW, npm team was deprecated `peerDependency`.

**Comment by ai** [comment]
Any updates here? React 0.13 ChangeLog doesn’t contain any react-jade specific changes, as I understand.

**Comment by TimothyGu** [comment]
0.13.0 breaks compatibility with 0.12.* so I'm not sure if we could update without bumping major.

But regardless of semver stuff, I have tried to update it and all tests pass right now.

```diff
diff --git a/package.json b/package.json
index 0f9f982..9993a04 100644
--- a/package.json
+++ b/package.json
@@ -19,12 +19,12 @@
     "htmlparser2": "~3.7.1",
     "istanbul": "^0.3.2",
     "marked": "~0.3.2",
-    "react": "~0.12.0",
+    "react": "~0.13.0",
     "rimraf": "~2.2.8",
     "testit": "~1.2.0"
   },
   "peerDependencies": {
-    "react": "~0.12.0"
+    "react": "~0.13.0"
   },
   "scripts": {
     "test": "node test/download-jade-tests.js && node test/index.js && npm run coverage",
```

**Comment by ai** [comment]
@TimothyGu this is not your dependency, only a peer dependency. But we can bump major version :).

**Comment by ForbesLindesay** [comment]
We don't need to bump the major version until we remove support for react 0.12.0, so all you need to do is update the peerDepenencies field to `>=0.12.0 <0.14.0`.  Then we just need to keep updating `0.14.0` each time a new version of react is released and updating `0.12.0` each time we stop supporting an old version of react.  @jeromew can probably publish a new version if someone submits a pull request.

**Comment by ai** [comment]
@ForbesLindesay maybe we should remove `peerDepenencies` because it is depreacted?

**Comment by ForbesLindesay** [comment]
I can't find any documentation that would back up that claim.  If they were deprecated it would be a disaster for maintainers of modules like this one.

**Comment by ai** [comment]
@ForbesLindesay here is `npm` thread https://github.com/npm/npm/issues/5080

I totally agree about disaster, but npm team thinks that it should be on app level https://github.com/npm/npm/issues/5080#issuecomment-40545825

For example, I insert app-level plugin version check to [PostCSS](https://github.com/postcss/postcss)

**Comment by ai** [comment]
@ForbesLindesay `peerDepenencies` will be deprreacted in npm@3. So we can use it right now.

Anyway I need React 0.13 quickly ^_^.

**Comment by hemanth** [comment]
+1 for React 0.13 from my side :)

**Comment by ForbesLindesay** [comment]
Where in that discussion does it actually say that peer dependencies are being deprecated?  All I see is lots of people expressing opinions (mostly misguided)

**Comment by ai** [comment]
@ForbesLindesay it was just a topic starter. Here is a continue https://github.com/npm/npm/issues/6565

Right not it is not depreacted. But many developers from npm team want to depreacted it.

Let’s just update `peerDepenencies`, React 0.13 is more impoortant rather that `peerDepenencies` discussion.

**Comment by ai** [comment]
@ForbesLindesay right now I can’t add react-jade to my project, because I need ES6 class notation from React 0.13.

**Comment by ForbesLindesay** [comment]
I agree. I will merge as soon as I see a pull request

**Comment by ai** [comment]
@ForbesLindesay PR #41

**Comment by ForbesLindesay** [comment]
This is now released.

**Comment by bjrmatos** [comment]
Actually `peerDependencies` wont be deprecated, just its behavior is changed, i was confused too, but after reading all coments in npm/npm#6565 everything is clear.
