### ISSUE TITLE
Using locals

### ISSUE THREAD

**Issue by azukaar** [jadejs/react-jade#53]
Hello !
I have quite a problem to understand how to transfer the locals to Jade-React ( and it seems like there's nearly no doc on it).
Basically I have my React.createClass thingy with a render methods :

render : ->
    return  jade.compileFile("./public/test.jade")(????)

And I can't figure out what to put inside the "locals" parameters to be able to use the this.props.* provided by ReactJS inside my template.

I tested a lot of things but always getting neither nothing or an error (for exemple I'm sometime getting Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(...)(...) is not a function when trying :
return  jade.compileFile("./public/test.jade")({list : "test"})()
)

Otherwisem rendering work (but I have no access to any locals, neither ReactJS's one or not even the one I'm trying to set manually)

Hope you can help, Thanks for reply, keep up the good work !

**Comment by jeromew** [comment]
I am in a hurry so won't be able to answer but you can check this test :
https://github.com/jadejs/react-jade/blob/master/test/index.js#L177
the test creates 2 react component and composes them. it also uses `locals`

**Comment by azukaar** [comment]
Thanks for reply I'll test this as soon as I get back to work on monday. Is the SubComponent used in the test a React defined var ? 
That's funny cause it seems like the locals aren't passed though Jada via the compile() routine like it should 
 var render2 = jade.compileFile(bonusDir + '/' + name + '.jade').locals({SubComponent: SubComponent});

But are directy injected in the React rendering phase 
var html = React.renderToStaticMarkup(React.createElement(c, { title: 'Jade', items: [ 'a', 'b', 'c' ]}));

Anyway I'll try this out and update this thread, thanks a lot !

**Comment by azukaar** [comment]
OK so I'm, and I figured out the issue : I don't think this is a normal comportement in the setup, it must be related to a bug in React-Jade to me. Basically, locals simply works that way :
 
    render : jade.compileFile("./public/test.jade"); 

BUT inside the template itself, the local won't be rendered if it doesn't perfectly match the pattern :
    tag= local

For exemple 

    div 
        this.props.title
or

    div this.props.title

will render    
    
    <this class="props title"></this>

Also,

    div
        | this.props.title

won't do the trick neither as it simply write " this.props.title" as a String  

    div= this.props.title

Only this will work.

It might be a problem to have such strictness upon template writing, by the way, the non-working pattern's equivalents using pure JSX are actually working, by that I mean that thanks to the bracets, JSX allow you to input any local in a very flexible way.

May be we should consider either implementing {} inside React-Jade (or may be an equivalent syntax already exists ?) or may be blacklist the "this" string from being used as a tag-name ?

Tell me what you think.

**Comment by jeromew** [comment]
the use cases you mention seem perfectly legit to me.

For example in jade when you write

    div this.props.title

the `this.props.title` part is not considered to be javascript. It would be the same as

    div Hello World !

you have to write

    div= this.props.title

so imho this is not a problem with `react-jade` but more with the way you expect jade to work.

you could also write

    div Hello #{this.props.title}

to approach what JSX is doing.

**Comment by azukaar** [comment]
OK I get your point. 

Actually what misled me is that I was sure that

    <div onclick="alert({this.props.name})">Hello {this.props.name}</div>

Would actually work with JSX, but it obviously don't, my bad.

Thanks !

**Comment by ForbesLindesay** [comment]
I'm going to close this issue as react-jade is doing the correct thing here.  Really we just need more/better documentation, which we will get once I get around to completing a redesign of the jade website.
