### ISSUE TITLE
problem with browserify,jsx, and compile jade files

### ISSUE THREAD

**Issue by royroev** [jadejs/react-jade#57]
Please, help me. Sorry my english. 

```js
/** @jsx React.DOM */
var React = require("react");
var Templates = require("../../public/templates/base")['JST'];  - returns a function that returns a jade template
var jade  = require('react-jade');
var itemSmall = jade.compileFile(__dirname + '/../view/templates/itemSmall.jade'); - it work
var itemBig = jade.compile(Templates.itemBig());  - don,t work!!! in console - jade is not defined 

var GetItem = React.createClass({
    render : function() {
        switch (this.props.size) {
            case 'small'  :  return (itemSmall({item : this.props.item})); break;
            case 'big'  :  return (itemBig({item : this.props.item})); break; - don't work!!!
            default : return ('')
        }
    }
});

module.exports = GetItem;
```

gulpfile - 

```js
....
function browserifyShare() {
    var b = browserify({
        entries : ['./app/browser/app.jsx'],
        debug : true,
        cache: {},
        packageCache: {},
        fullPaths: true,
        insertGlobals: true,
        transform: [reactify, reactJade]
    });
    b = watchify(b);
    b.on('update', function () {
        bundleShare(b);
    });

    bundleShare(b);
}

function bundleShare(b) {
    b.bundle()
        .pipe(source('bundle.dev.js'))
        .pipe(gulp.dest('public/scripts'))
        .pipe($.livereload());
}
```

**Comment by ForbesLindesay** [comment]
`jade.compile(Templates.itemBig());` can't be analysed by the jade transform because the text returned by `Templates.itemBig()` is not yet known.  If you have the string directly you can do something like:

```js
var template = jade.compile('h1 Example Jade Template');
```

This works because we know the value being given to `jade.compile` at compile time.

If you have to generate the jade at runtime you will need to remove the `reactJade` transform, so that jade is compiled at runtime.  This will be much slower though, and may not work in older browsers.

**Comment by ForbesLindesay** [comment]
I've closed the issue as this is expected behaviour.  Feel free to comment if you need more help though.

**Comment by royroev** [comment]
if i remove reactJade in transform in console Error - Uncaught TypeError: fs.readFileSync is not a function in compiler.js 
if i use jade.compileFile(__dirname + '/../view/templates/itemSmall.jade') it kill me, because I have a big project.
What can you advise?

**Comment by ForbesLindesay** [comment]
Write a small node.js script to generate a `jade.compileFile` call for each view?
